---
- hosts: all
  become: true
  vars:
    ssh_keys_dir: "./ssh-keys"  
  tasks:
    - name: check if directory is there
      ansible.builtin.file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0700'

    - name: check if keys exist
      ansible.builtin.file:
        path: /home/vagrant/.ssh/authorized_keys
        owner: vagrant
        group: vagrant
        mode: '0600'
        state: touch

    - name: Add 
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "{{ ssh_keys_dir }}/*.pub"

    - name: swap for running system
      ansible.builtin.shell: swapoff -a

    - name: swap entry remove
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: 'swap'
        state: absent

    - name: for net.ipv4.ip_forward
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        state: present
        sysctl_set: yes

    - name: for net.bridge.bridge-nf-call-iptables
      ansible.builtin.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        state: present
        sysctl_set: yes

    - name: for net.bridge.bridge-nf-call-ip6tables
      ansible.builtin.sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        state: present
        sysctl_set: yes

    - name: cluster hostnames step 8
      ansible.builtin.blockinfile:
        path: /etc/hosts
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        backup: yes
        block: |
          {{ ctrl_ip }} ctrl
          {% for i in range(1, worker_count + 1) %}
          {{ worker_ip_base }}{{ 100 + i }} node-{{ i }}
          {% endfor %}

    #step 9:

    - name: Kubernetes apt key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
        state: present

    - name: Kubernetes repo
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /"
        state: present

    - name: apt cache update
      ansible.builtin.apt:
        update_cache: yes

    #step 10 - install required (removed version due to issues for now)
    - name: Install containerd and runc
      ansible.builtin.apt:
        name:
          - containerd
          - runc

    - name: Install Kubernetes tools
      ansible.builtin.apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
          
