---
- hosts: all
  become: true
  vars:
    ssh_keys_dir: "./ssh-keys"
  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0700'

    - name: Ensure authorized_keys file exists
      ansible.builtin.file:
        path: /home/vagrant/.ssh/authorized_keys
        owner: vagrant
        group: vagrant
        mode: '0600'
        state: touch

    - name: Add SSH public keys from shared folder
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "{{ ssh_keys_dir }}/*.pub"

    - name: Disable swap
      ansible.builtin.command: swapoff -a
      when: ansible_swaptotal_mb | default(0) > 0

    - name: Remove swap from fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^.*swap.*$'
        state: absent

    - name: Ensure swap is disabled with mount module
      ansible.builtin.mount:
        name: swap
        fstype: swap
        state: absent
    - name: Ensure Kubernetes kernel modules are configured to load at boot
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: '0644'

    - name: Ensure overlay kernel module is loaded
      modprobe:
        name: overlay
        state: present

    - name: Ensure br_netfilter kernel module is loaded
      modprobe:
        name: br_netfilter
        state: present

    - name: Enable IPv4 forwarding
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes
        sysctl_set: yes

    - name: Enable bridged iptables
      ansible.builtin.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        state: present
        reload: yes
        sysctl_set: yes

    - name: Enable bridged ip6tables
      ansible.builtin.sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: '1'
        state: present
        reload: yes
        sysctl_set: yes

    - name: Render hosts template
      ansible.builtin.template:
        src: /vagrant/ansible/templates/hosts_block.j2
        dest: /tmp/hosts_block

    - name: Insert hosts block
      ansible.builtin.blockinfile:
        path: /etc/hosts
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: "{{ lookup('file', '/tmp/hosts_block') }}"
        backup: yes

    - name: Ensure apt keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Download Kubernetes apt repository key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: '0644'
      register: kubernetes_repo_key

    - name: Inspect existing Kubernetes apt keyring
      ansible.builtin.stat:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      register: kubernetes_keyring_stat

    - name: Convert Kubernetes apt key to keyring format
      ansible.builtin.command:
        argv:
          - gpg
          - --dearmor
          - --yes
          - -o
          - /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          - /etc/apt/keyrings/kubernetes-apt-keyring.asc
      when: kubernetes_repo_key.changed or not kubernetes_keyring_stat.stat.exists
      changed_when: kubernetes_repo_key.changed or not kubernetes_keyring_stat.stat.exists

    - name: Add Kubernetes apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
        state: present
        filename: kubernetes

    - name: Update apt cache after adding Kubernetes repository
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install container runtime packages
      ansible.builtin.apt:
        name:
          - containerd
          - runc
        state: present

    - name: Install Kubernetes tools
      ansible.builtin.apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
