---
- hosts: all
  become: true

  vars:
    ssh_keys_dir: "{{ playbook_dir }}/../ssh-keys"
    ctrl_ip: "192.168.56.100"
    worker_ip_base: "192.168.56."
    worker_count: 2

  tasks:
    # Step 4: SSH keys
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0700'

    - name: Add team SSH public keys without removing Vagrant’s default key
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      loop: "{{ lookup('fileglob', ssh_keys_dir ~ '/*.pub', wantlist=True) }}"

    - name: swap for running system
      ansible.builtin.shell: swapoff -a

    - name: swap entry remove
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: 'swap'
        state: absent
