---
- hosts: all
  become: true
  vars:
    ssh_keys_dir: "./ssh-keys"
  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0700'

    - name: Ensure authorized_keys file exists
      ansible.builtin.file:
        path: /home/vagrant/.ssh/authorized_keys
        owner: vagrant
        group: vagrant
        mode: '0600'
        state: touch

    - name: Add SSH public keys from shared folder
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "{{ ssh_keys_dir }}/*.pub"

    - name: Disable swap
      ansible.builtin.command: swapoff -a
      when: ansible_swaptotal_mb | default(0) > 0

    - name: Remove swap from fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^.*swap.*$'
        state: absent

    - name: Ensure swap is disabled with mount module
      ansible.builtin.mount:
        name: swap
        fstype: swap
        state: absent

    - name: Ensure Kubernetes kernel modules are configured to load at boot
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: '0644'

    - name: Ensure overlay kernel module is loaded
      modprobe:
        name: overlay
        state: present

    - name: Ensure br_netfilter kernel module is loaded
      modprobe:
        name: br_netfilter
        state: present
