apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deployment.fullname" . }}-secret
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
type: Opaque
stringData:
  smtpUsername: {{ .Values.smtp.username | quote }}
  smtpPassword: {{ .Values.smtp.password | quote }}
