{
 "title": "SMS metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SMS classification requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(sms_classification_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Classification throughput",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(sms_classification_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMS classification results (increase)",
   "type": "timeseries",
   "description": "The amount of classification results in the last `$__rate_interval` per class",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum by (result) (\r\n    increase(sms_classification_results_total[$__rate_interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMS message length",
   "type": "heatmap",
   "description": "Distribution of SMS message lengths in characters",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (\r\n  rate(sms_message_length_chars_bucket[$__rate_interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest message length",
   "type": "gauge",
   "description": "Length of latest processed message in characters\n\n`max(latest value of all pods)`",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "chars" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sms_current_message_length_chars{namespace=\"default\", service=\"app\", type=\"current\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMS classification duration",
   "type": "heatmap",
   "description": "Time taken to classify SMS messages in seconds",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (\r\n  rate(sms_classification_duration_milliseconds_bucket[$__rate_interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}